apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-blue-$BUILD
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: webserver
        color: $BUILD
    spec:
      containers:
      - image: 192.168.99.1:5000/rmrbest/spring-boot-playground:$BUILD
        name: spring-boot-container
        ports:
        - containerPort: 8081
          name: http-server
